repos:
  - repo: local

    hooks:
      - id: yapf
        name: yapf
        entry: yapf
        language: system
        types: [python]
        args: ["--style=setup.cfg", "--in-place"]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: ["--config=setup.cfg"]
